---
- name: Copy cloud-config for VM1
  copy:
    src: ../files/config_vm1.iso
    dest: /var/lib/libvirt/images/global_logic/config_vm1.iso
  become: yes

- name: Copy cloud-config for VM2
  copy:
    src: ../files/config_vm2.iso
    dest: /var/lib/libvirt/images/global_logic/config_vm2.iso
  become: yes
