---

- name: Install KVM and Cloud-init
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - qemu-kvm
    - libvirt-bin
    - ubuntu-vm-builder
    - bridge-utils
    - virt-manager
    - cloud-init
  become: yes

- name: Start/Enable libvirtd
  systemd:
    state: started
    name: libvirtd
  become: yes

- name: Check if the libvirt module is loaded
  shell: "lsmod | grep kvm | wc -l"
  become: yes
  register: libvirt_mod_loaded

- fail:
    msg: "libvirt module is not loaded."
  when: libvirt_mod_loaded.stdout == '0'