---

- name: Create Dir for KVM result log
  file: "state=directory path={{ data_dir }} force=yes mode=0777"
  become: yes
  delegate_to: "{{ kvm_install_host }}"

- name: KVM Install
  import_tasks: install.yaml

#TEST

- name: Test_KVM_Install
  shell: "virsh -c qemu:///system list"
  become: yes
  delegate_to: "{{ kvm_install_host }}"
