---

- name: Create Dir for KVM result log
  file: "state=directory path={{ data_dir }} force=yes mode=0777"
  become: yes

- name: KVM Install
  import_tasks: install.yaml

- name: Test_KVM_Install
  shell: "virsh -c qemu:///system list"
  become: yes
