- hosts: localhost
  tasks:
    - name: Start VMs
      include_role:
        name: vm_start

    - name: Wait for SSH come up.
      wait_for:
        port: 22
        host: "{{ hostvars['worker1'].ansible_host }}"
        delay: 30
        timeout: 60

    - name: Wait for SSH come up.
      wait_for:
        port: 22
        host: "{{ hostvars['worker2'].ansible_host }}"
        delay: 30
        timeout: 60